### ISSUE TITLE
TcpServer is not a constructor

### ISSUE THREAD

**Issue by DPassarelli** [svrooij/tcp-server#2]
Hi, I am attempting to replicate the sample code from your README, but it will not execute on my machine.

Machine specs:
* macOS 10.15.5 (Catalina)
* Node.js v12.18.1
* npm 6.14.5

Package.json:
```
{
  "name": "telnet-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@svrooij/tcp-server": "^1.0.1"
  }
}
```

index.js:
```
const TcpServer = require('@svrooij/tcp-server')

const server = new TcpServer({ port: 3000, host: '0.0.0.0' })
server.start()

server.on('textReceived', (text, remoteAddress) => {
  console.log('%s -> %s', remoteAddress, text)
})

server.publish('Publish message').then(success => {
  console.log('Message send ', success ? ' successfully' : 'failed')
})

process.on('SIGINT', () => {
  console.log('Stopping server')
  server.stop()
})
```

Error message:
```
Mon Jun 22 19:50:24 
(imac) ~/Repositories/personal/telnet-test $ node index.js
/Users/dpassarelli/Repositories/personal/telnet-test/index.js:3
const server = new TcpServer({ port: 3000, host: '0.0.0.0' })
               ^

TypeError: TcpServer is not a constructor
    at Object.<anonymous> (/Users/dpassarelli/Repositories/personal/telnet-test/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

Mon Jun 22 19:50:29 the last command exited with code 1
```

I've scanned the source code, but nothing seems obvious to me at first glance. If I clone your repository locally and run `npm test`, everything passes except for `sends json to client` (which I am not 100% concerned about).

Would you be willing to check (and possibly update) your sample code, and/or ensure that your tests are actually exercising the transpiled code? Something doesn't seem to add up here.

Thanks!
David

**Comment by svrooij** [comment]
I think this [commit](https://github.com/svrooij/tcp-server/commit/ede75b45aa2f841bd09299761a70172236b4e48a) changed the exports from being at the base of the library to having multiple exports.

So the code needed changing from
```JS
const TcpServer = require('@svrooij/tcp-server')
// to
const TcpServer = require('@svrooij/tcp-server').TcpServer
```
